<template>
  <div id="container">
    <v-content>
       <p><strong>Terms of Service</strong></p>
    <p><strong>SkoolAide LLC (herein &ldquo;SkoolAide&rdquo; or &ldquo;we&rdquo;) maintains this corporate website (the &ldquo;Service&rdquo;) subject to the terms and conditions, copyright notices, and trademark information described below. Your use of the Service constitutes an agreement by you to abide by these terms, notices, and conditions.</strong></p>
    <p><strong>Disclaimer of Warranties</strong> &mdash; This Service is available &ldquo;as is&rdquo;. We do not warrant that this Service will be uninterrupted or error-free. There may be delays, omissions, interruptions and inaccuracies in the news, information or other materials available through this Service. We are not responsible for the availability or content of other services that may be linked to this Service. We do not make any warranties, express or implied, including without limitation, those of merchantability and fitness for a particular purpose, with respect to this Service or any information or goods that are available or advertised or sold through this Service.</p>
    <p>We do not make any representations, nor do we endorse the accuracy, completeness, timeliness or reliability of any advice, opinion, statement or other material or database displayed, uploaded or distributed in this Service or available through links in this Service. We reserve the right to correct any errors or omissions in this Service. Although we intend to take reasonable steps to prevent the introduction of malware, viruses, worms, &ldquo;Trojan horses&rdquo; or other destructive materials to this Service, we do not guarantee or warrant that this Service or materials that may be downloaded from this Service do not contain such destructive features. We are not liable for any damages or harm attributable to such features. If you rely on this Service and any materials available through this Service, you do so solely at your own risk.</p>
    <p><strong>Limitation of Liability</strong> &mdash; SkoolAide, its officers, directors, shareholders, parents, subsidiaries, affiliates, agents, or licensors are not liable for incidental, indirect, consequential, special, punitive, or exemplary damages of any kind, including lost revenues or profits, loss of business or loss of data, in any way related to this Service or for any claim, loss or injury based on errors, omissions, interruptions or other inaccuracies in this Service (including without limitation as a result of breach of any warranty or other term of this Agreement). Any claim against us shall be limited to the amount you paid, if any, for use of this Service.</p>
    <p><strong>Indemnification</strong> &mdash; You agree to indemnify and hold harmless SkoolAide, its directors, officers, shareholders, parents, subsidiaries, affiliates, agents, and licensors, from and against all losses, expenses, damages and costs, including reasonable attorneys&rsquo; fees, resulting from any violation by You of this Agreement. We reserve the right to take over the exclusive defense of any claim for which we are entitled to indemnification under this Section. In such event, you shall provide us with such cooperation as is reasonably requested by us.</p>
    <p><strong>Copyright Notice</strong> &mdash; The contents of this Service (including, but not limited to text, photographs, graphics, video and audio content) is protected under the copyright laws of the United States. You agree to abide by all copyright notices and/or restrictions contained in this Service. You may not copy, reproduce, distribute, publish, enter into a database, display, perform, modify, create derivative works, transmit, or in any way exploit any part of this Service, except that you may download material from this Service for your own personal use. Without limiting the generality of the foregoing, you may not distribute any part of this Service over any network, including a local area network, nor sell or offer it for sale. In addition, these files may not be used to construct any kind of database.</p>
    <p><strong>Trademarks</strong> &mdash; SkoolAide, SkoolAide Academic Performance Platform, SkoolAide MyVoice are registered trademarks and the SkoolAide logo are trademarks of SkoolAide LLC Where one of these trademarks is used, include the appropriate trademark symbol (e.g., &reg; or &trade;) followed by the appropriate attribution &mdash; for example, &ldquo;_____ is a trademark of SkoolAide LLC&rdquo; This site also refers to certain third-party trademarks, including those that follow.</p>
    <p><strong>Amendments and Modifications</strong> &mdash; SkoolAide reserves the right to amend the information, services, and/or content of this Service. The information and materials contained in this Service, and the terms and conditions of the access to and use of such information and materials, are subject to change. In the event of a material change to this Agreement, a notice will be posted to the Service. If you use this Service after we post changes to the terms, you agree to accept the changed terms. SkoolAide expressly reserves the right to monitor any and all use of this Service.</p>
    <p><strong>Entire Agreement </strong>&mdash; Unless otherwise specified, this Agreement constitutes the entire agreement between you and SkoolAide with respect to the Service and supersedes all prior or contemporaneous communications and proposals (whether oral, written, or electronic) between you and SkoolAide with respect to the Service.</p>
    <p><strong>Severability</strong> &mdash; In the event any paragraph or portion of any paragraph of this Agreement shall be determined to be invalid or unenforceable for any reason, such invalidity of unenforceability shall not affect the validity and enforceability of the remaining valid and enforceable paragraphs hereof, and shall be the invalid or unenforceable portion shall be deemed amended but only to the extent necessary to make such portion enforceable and compatible with the remaining terms of this Agreement, and if such portion cannot be so amended the Agreement will be construed as if such invalid or unenforceable paragraph or portion had not been inserted.</p>
    <p><strong>Governing Law</strong> &mdash; This Agreement shall be governed by and construed in accordance with the laws of the state of North Carolina, without regard to conflict of law rules, and each party hereto hereby consents to the submission of any dispute arising hereunder to the federal or state courts located within North Carolina and Mecklenburg County and submits to the jurisdiction of such court for the purpose of resolution of any claim hereunder.&nbsp;</p>
    </v-content>
  </div>
   
</template>

<script>
export default {
  

}
</script>

<style>

</style>
